#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap


if [ -f "config.toml" ]; then
    (git submodule update --init)
    (zola build)
    echo "==> App is now ready to go! do 'zola serve' to see output."
fi
